### PR TITLE
Fix ModelOffsetY behavior

### LINKED ISSUE #19: 1.1.1 ModelOffsetY float glitch
When I increase ModelOffsetY in settings_player to a value above 0.00, the player model will float + ascend upwards into the air. I've troubleshooted by reinstalling Valheim, but it seems to be ModelOffsetY causing the issue.

This was not happening in previous versions however, and seems to be exclusive to 1.1.1; In the meantime, I'll play the older versions.

(Thank you so much for this incredible mod, by the way! This has to be my favorite mod of all time. 😄❤️)

### PR DESCRIPTION
**Pull request by ParoPew**
Fixed #19 -- Also fixes some issues with weapon/hand alignment when using ModelOffsetY

### CODE REVIEW

**Comment by yoship1639** [comment]
I'll check later, Thanks!

**Comment by Fenneky** [comment]
One question. Where do i put this File? I did put it in Plugin and Valheim_Data/managed but nothing changed, got the same floating-bug.

**Comment by ParoPew** [comment]
> One question. Where do i put this File? I did put it in Plugin and Valheim_Data/managed but nothing changed, got the same floating-bug.

You would need to build the project and replace the DLL in the plugins folder. I have the built DLL on my forked repo:
https://github.com/ParoPew/ValheimVRM/releases/tag/ver1.1.2

With the Y offset option there is still the odd issue where the walk cycle slightly sinks but it is tolerable. Haven't looked in too much how to fix it. Moving the feet bones by any amount is the main trigger for getting launched in to space :)

**Comment by yoship1639** [comment]
Sorry for the delay. I have not been able to check everything, but it looks fine.
Thank you very much!

**Pull request merged**
